# config/.gosast.yml

linters:
  gosec:
    enabled: true
  staticcheck:
    enabled: true
  custom:
    enabled: true
    rules:
      - sql_injection
      - command_injection
      - xss
      - weak_authentication
      - sensitive_data_exposure
      - xxe
      - broken_access_control
      - security_misconfiguration
      - insecure_deserialization
      - dependency_vulnerabilities
      - logging
      - resource_management
      - input_validation
      - path_traversal
      - error_handling

severity_levels:
  critical:
    - sql_injection
    - command_injection
    - weak_authentication
    - cryptography
  high:
    - xss
    - sensitive_data_exposure
    - broken_access_control
    - security_misconfiguration
    - path_traversal
  medium:
    - insecure_deserialization
    - dependency_vulnerabilities
    - logging
    - resource_management
  low:
    - input_validation
    - error_handling
